version: "3.8"

services:

   django_rest:
    build:
        context: ./backend
        dockerfile: DockerfileBackend
    command: coreRest init
    volumes:
      - backend-app:/work
    ports:
      - "8000:8000"

   front:
    build:
        context: .
        dockerfile: DockerfileFrontend
    ports:
      - "8080:8080"
    volumes:
      - vue-app:/app

volumes:
  vue-app:
    driver: local
    driver_opts:
      type: none
      device: /absolute/pathofDockerCompose
      o: bind

  backend-app:
    driver: local
    driver_opts:
      type: none
      device: /absolute/pathofDockerCompose/backend
      o: bind
